name: food_pos

packages:
  - .
  - packages/*

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  gen:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      flutter: true

  gen:intl:
    run: |
      melos run gen:intl:shared --no-select
      melos run gen:intl:feature --no-select

  gen:intl:shared:
    exec: dart run intl_utils:generate
    packageFilters:
      flutter: true
      scope: ["core", "ui"]

  gen:intl:feature:
    exec: dart run tools:merge_l10n
    packageFilters:
      flutter: true
      ignore: ["core", "ui"]
