name: uni_q_application
description: "A new Flutter project."
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_gen: ^5.10.0
  go_router: ^16.2.0
  melos: ^6.3.2
  intl_utils: ^2.8.8
  core:
    path: packages/core
  ui:
    path: packages/ui
  tools:
    path: packages/tools
  auth:
    path: packages/auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.1
  flutter_gen_runner: ^5.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
    - assets/videos/
  fonts:
    - family: LineSeedSansTH
      fonts:
        - asset: ./assets/fonts/LINESeedSansTH_A_Rg.ttf
          weight: 400
        - asset: ./assets/fonts/LINESeedSansTH_A_Bd.ttf
          weight: 500

flutter_gen:
  output: lib/src/generated/
  line_length: 80

flutter_intl:
  enabled: true
  main_locale: th
  class_name: AppLocalizations
  arb_dir: lib/src/generated/localization
  output_dir: lib/src/generated

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false

scripts:
  generator:
    build: flutter pub run build_runner build --delete-conflicting-outputs
    watch: flutter pub run build_runner watch --delete-conflicting-outputs

  merge-l10n: dart run tools/merge_l10n.dart

  install: flutter pub get

  reset: |
    flutter clean
    flutter pub get

  # Aliases
  gb: rps generator build && dart run build_runner build --delete-conflicting-outputs
  gw: rps generator watch
  ml: rps merge-l10n
  icon: dart run flutter_launcher_icons
  assets: dart run build_runner build --delete-conflicting-outputs

lint_staged:
  "lib/**.dart": dart format && dart fix --apply
