name: auth
description: "Auth package for Flutter application."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  core:
    path: ../core
  ui:
    path: ../ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  intl_utils: ^2.8.7
  tools:
    path: ../tools

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: th
  class_name: AuthLocalizations
  arb_dir: lib/src/generated/localization
  output_dir: lib/src/generated
